name: dockerize

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        default: 'dev'

jobs:
  build:
    name: Publish Cohere Terrarium Docker Images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Get all history to correctly infer Khoj version using hatch
          fetch-depth: 0

      - name: 🧹 Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}

      - name: 🧹 Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: 📦️⛅️ Build and Push Cloud Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ${{ github.ref_type == 'tag' && format('ghcr.io/{0}:latest', github.repository) || '' }}
